## Configuration for the training, evaluation
samples:

#   - name: ttbar_test1
#     path: /store/hep/users/yewzzang/saja/ttbar_pt_v1/ttbar_4180.pt
#   - name: ttbar_test1
#     path: /store/hep/users/yewzzang/saja/ttbar_pt_v1/ttbar_950.pt
#   - name: ttbar_test1
#     path: /store/hep/users/yewzzang/saja/ttbar_pt_v1/ttbar_93.pt
   
#   - name: ttbar_test2
#     path: /store/hep/users/yewzzang/saja/ttbar_pt_v2/ttbar_8650.pt
#   - name: ttbar_test2
#     path: /store/hep/users/yewzzang/saja/ttbar_pt_v2/ttbar_9940.pt
#   - name: ttbar_test2
#     path: /store/hep/users/yewzzang/saja/ttbar_pt_v2/ttbar_2210.pt


  - name: ttbar_v1
    path: /store/hep/users/yewzzang/saja/ttbar_pt_v1/*.pt
    
  - name: ttbar_v2
    path: /store/hep/users/yewzzang/saja/ttbar_pt_v2/*.pt

training:
    nDataLoaders : 16
    splitFractions : [0.7, 0.2] ## training set, validation set. (test set is the reminders)
    epoch : 100
    batch : 512
    learningRate : 0.0001
    randomSeed : 12345

    
model:
    fea : 5
    model: 'SAJA'
    cla : 5
    hidden : 32
    heads : 10
    posfeed : 1024
    dropout : 0.1
    depths : 6
     
    