## Configuration for the training, evaluation
samples:


  - name: ttbar
    path: /store/hep/users/yewzzang/saja/TTbar_pt/*.pt
    


training:
    nDataLoaders : 16
    splitFractions : [0.7, 0.2] ## training set, validation set. (test set is the reminders)
    epoch : 500
    batch : 512
    learningRate : 0.0001
    randomSeed : 12345

    
model:
    fea : 5
    model: 'SAJA'
    cla : 5
    hidden : 32
    heads : 10
    posfeed : 1024
    dropout : 0.1
    depths : 6
     
    